### PR TITLE
hide banner image when video loads

### PR DESCRIPTION
**Pull request by vivek12345**
When the video loads, banner image is still being shown

screenshot 2018-11-05 at 10 56 53 am

- I have updated the code to set showBanner to false when videoLoad is true
- Ran yarn build to generate new stats.json and new client and server bundle.

`Please help me review this and test it once before deploying on master.`

@manjula91 @vihangpatel @Anjali2210 

`website after these changes`
screenshot 2018-11-05 at 10 57 03 am

### CODE REVIEW

**Comment by VivekNayyar** [comment]
@manjula91 it seems the build exceeded time and failed. Can you restart and check it once

**Comment by manjula91** [comment]
sure :)

**Comment by vihangpatel** [comment]
@vivek12345 , in some browsers it does not load. So if you set the flag to false, it will hide the image for unsupported browser. This is for poor browsers & kept intentionally .

**Comment by VivekNayyar** [comment]
Alright fair point. If it's too much of a change let's leave it here. I was just thinking for an unsupported browser should we even try loading a video. As in the poor browsers can have an initial check for video support right?

**Comment by vihangpatel** [comment]
Although flag value can be set using `modernize` lib, which will be like
`
this.setState({
      showBanner: !videoSupportTestFnCall
})
`

**Comment by VivekNayyar** [comment]
Alright that would make sense. But don't put in much time into this if we have other important fixes to do.

**Pull request closed without merging**
